/* Community system migration for BolChel.github.io
   Run once in Supabase SQL Editor. */
begin;

alter table public.profiles add column if not exists created_at timestamptz;
update public.profiles p set created_at=coalesce(p.created_at,u.created_at,now()) from auth.users u where u.id=p.id and p.created_at is null;
update public.profiles set created_at=now() where created_at is null;
alter table public.profiles alter column created_at set default now(), alter column created_at set not null;
alter table public.profiles add column if not exists is_banned boolean not null default false, add column if not exists ban_reason text, add column if not exists banned_at timestamptz, add column if not exists banned_by uuid;

do $$
declare keep_owner uuid;
begin
  select id into keep_owner from public.profiles where role='owner' order by created_at asc,id limit 1;
  if keep_owner is null then
    select id into keep_owner from public.profiles where role='admin' order by created_at asc,id limit 1;
    if keep_owner is not null then update public.profiles set role='owner' where id=keep_owner; end if;
  end if;
  if keep_owner is not null then update public.profiles set role='admin' where role='owner' and id<>keep_owner; end if;
end $$;

do $$
declare c record;
begin
  for c in
    select con.conname from pg_constraint con
    join pg_class rel on rel.oid=con.conrelid
    join pg_namespace nsp on nsp.oid=rel.relnamespace
    where nsp.nspname='public' and rel.relname='profiles' and con.contype='c'
      and pg_get_constraintdef(con.oid) ilike '%role%'
  loop execute format('alter table public.profiles drop constraint if exists %I',c.conname); end loop;
end $$;

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check(role in('reader','admin','owner'));
create unique index if not exists profiles_single_owner_idx on public.profiles(role) where role='owner';
create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists profiles_banned_idx on public.profiles(is_banned) where is_banned=true;

create or replace function public.community_current_role()
returns text language sql stable security definer set search_path=''
as $$ select p.role from public.profiles p where p.id=(select auth.uid()) $$;
revoke all on function public.community_current_role() from public;
grant execute on function public.community_current_role() to anon,authenticated;

create or replace function public.community_is_banned(p_user_id uuid default null)
returns boolean language sql stable security definer set search_path=''
as $$ select coalesce((select p.is_banned from public.profiles p where p.id=coalesce(p_user_id,(select auth.uid()))),false) $$;
revoke all on function public.community_is_banned(uuid) from public;
grant execute on function public.community_is_banned(uuid) to anon,authenticated;

create or replace function public.community_can_manage_user(p_target_id uuid)
returns boolean language plpgsql stable security definer set search_path=''
as $$
declare me_role text; target_role text;
begin
  if (select auth.uid()) is null or p_target_id is null then return false; end if;
  select role into me_role from public.profiles where id=(select auth.uid());
  select role into target_role from public.profiles where id=p_target_id;
  if target_role is null or target_role='owner' then return false; end if;
  if me_role='owner' then return true; end if;
  return me_role='admin' and target_role='reader';
end $$;
revoke all on function public.community_can_manage_user(uuid) from public;
grant execute on function public.community_can_manage_user(uuid) to authenticated;

create table if not exists public.comments(
  id bigint generated by default as identity primary key,
  news_id text not null,
  author_id uuid not null references public.profiles(id) on delete cascade,
  parent_id bigint references public.comments(id) on delete cascade,
  body text not null,
  score integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint comments_body_length check(char_length(trim(body)) between 1 and 4000)
);
create index if not exists comments_news_id_idx on public.comments(news_id,created_at);
create index if not exists comments_parent_id_idx on public.comments(parent_id,created_at);
create index if not exists comments_author_id_idx on public.comments(author_id,created_at);

create table if not exists public.comment_reactions(
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  value smallint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint comment_reactions_value_check check(value in(-1,1)),
  constraint comment_reactions_one_per_user unique(comment_id,user_id)
);
create index if not exists comment_reactions_comment_id_idx on public.comment_reactions(comment_id);
create index if not exists comment_reactions_user_id_idx on public.comment_reactions(user_id);

create or replace view public.community_public_profiles
with(security_invoker=true) as
select p.id,p.nickname,p.role,p.avatar_url,p.bio,p.created_at,
coalesce((select sum(c.score) from public.comments c where c.author_id=p.id),0)::integer as comment_score,
(select count(*) from public.news n where n.author_id=p.id)::integer as publication_count
from public.profiles p;
grant select on public.community_public_profiles to anon,authenticated;

create or replace function public.community_list_users()
returns table(id uuid,nickname text,role text,avatar_url text,bio text,created_at timestamptz,comment_score integer,publication_count integer,is_banned boolean,ban_reason text)
language plpgsql stable security definer set search_path=''
as $$
begin
  if (select public.community_current_role())<>'owner' then raise exception 'Только владелец может просматривать список пользователей.'; end if;
  return query
  select p.id,p.nickname,p.role,p.avatar_url,p.bio,p.created_at,
    coalesce((select sum(c.score) from public.comments c where c.author_id=p.id),0)::integer,
    (select count(*) from public.news n where n.author_id=p.id)::integer,
    p.is_banned,p.ban_reason
  from public.profiles p
  order by case p.role when 'owner' then 0 when 'admin' then 1 else 2 end,p.nickname;
end $$;
revoke all on function public.community_list_users() from public;
grant execute on function public.community_list_users() to authenticated;

create or replace function public.community_validate_comment()
returns trigger language plpgsql security definer set search_path=''
as $$
declare parent_news text;
begin
  if not exists(select 1 from public.news n where n.id::text=new.news_id) then
    raise exception 'Новость для комментария не найдена.';
  end if;
  if new.parent_id is not null then
    select news_id into parent_news from public.comments where id=new.parent_id;
    if parent_news is null then raise exception 'Родительский комментарий не найден.'; end if;
    if parent_news<>new.news_id then raise exception 'Ответ должен относиться к той же новости.'; end if;
    if new.parent_id=new.id then raise exception 'Комментарий не может отвечать сам себе.'; end if;
  end if;
  return new;
end $$;
drop trigger if exists community_validate_comment on public.comments;
create trigger community_validate_comment before insert or update of news_id,parent_id on public.comments for each row execute function public.community_validate_comment();

create or replace function public.community_comment_timestamp()
returns trigger language plpgsql security definer set search_path=''
as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists community_comment_timestamp on public.comments;
create trigger community_comment_timestamp before update on public.comments for each row execute function public.community_comment_timestamp();

create or replace function public.community_reaction_score_trigger()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  if tg_op='INSERT' then update public.comments set score=score+new.value,updated_at=now() where id=new.comment_id; return new; end if;
  if tg_op='UPDATE' then if old.value<>new.value then update public.comments set score=score+(new.value-old.value),updated_at=now() where id=new.comment_id; end if; return new; end if;
  if tg_op='DELETE' then update public.comments set score=score-old.value,updated_at=now() where id=old.comment_id; return old; end if;
  return null;
end $$;
drop trigger if exists community_reaction_score on public.comment_reactions;
create trigger community_reaction_score after insert or update or delete on public.comment_reactions for each row execute function public.community_reaction_score_trigger();

create or replace function public.community_news_delete_comments()
returns trigger language plpgsql security definer set search_path=''
as $$ begin delete from public.comments where news_id=old.id::text; return old; end $$;
drop trigger if exists community_news_delete_comments on public.news;
create trigger community_news_delete_comments after delete on public.news for each row execute function public.community_news_delete_comments();

alter table public.comments enable row level security;
alter table public.comment_reactions enable row level security;
drop policy if exists community_comments_read on public.comments;
create policy community_comments_read on public.comments for select using(true);
drop policy if exists community_comments_insert on public.comments;
create policy community_comments_insert on public.comments for insert to authenticated with check((select auth.uid())=author_id and not (select public.community_is_banned((select auth.uid()))));
drop policy if exists community_comments_update_own on public.comments;
create policy community_comments_update_own on public.comments for update to authenticated using((select auth.uid())=author_id) with check((select auth.uid())=author_id);
drop policy if exists community_comments_delete_own on public.comments;
create policy community_comments_delete_own on public.comments for delete to authenticated using((select auth.uid())=author_id);
drop policy if exists community_reactions_read_own on public.comment_reactions;
create policy community_reactions_read_own on public.comment_reactions for select to authenticated using((select auth.uid())=user_id);
drop policy if exists community_reactions_insert on public.comment_reactions;
create policy community_reactions_insert on public.comment_reactions for insert to authenticated with check((select auth.uid())=user_id and not (select public.community_is_banned((select auth.uid()))));
drop policy if exists community_reactions_update on public.comment_reactions;
create policy community_reactions_update on public.comment_reactions for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
drop policy if exists community_reactions_delete on public.comment_reactions;
create policy community_reactions_delete on public.comment_reactions for delete to authenticated using((select auth.uid())=user_id);

create or replace function public.community_news_guard()
returns trigger language plpgsql security definer set search_path=''
as $$
declare me uuid:=(select auth.uid()); me_role text; old_author_role text;
begin
  if me is null then raise exception 'Требуется авторизация.'; end if;
  select role into me_role from public.profiles where id=me;
  if tg_op='INSERT' then
    if me_role not in('admin','owner') then raise exception 'Публиковать новости могут только администраторы и владелец.'; end if;
    return new;
  end if;
  select role into old_author_role from public.profiles where id=old.author_id;
  if me_role='owner' then if tg_op='DELETE' then return old; else return new; end if; end if;
  if me_role='admin' and (old.author_id=me or old_author_role='reader') then
    if tg_op<>'DELETE' and new.author_id is distinct from old.author_id and new.author_id<>me then raise exception 'Администратор не может передавать чужую новость другому пользователю.'; end if;
    if tg_op='DELETE' then return old; else return new; end if;
  end if;
  raise exception 'Недостаточно прав для этой новости.';
end $$;
drop trigger if exists community_news_guard on public.news;
create trigger community_news_guard before insert or update or delete on public.news for each row execute function public.community_news_guard();

create or replace function public.community_submission_guard()
returns trigger language plpgsql security definer set search_path=''
as $$
declare me uuid:=(select auth.uid()); me_role text; old_author_role text;
begin
  if me is null then raise exception 'Требуется авторизация.'; end if;
  select role into me_role from public.profiles where id=me;
  if tg_op='INSERT' then
    if new.author_id<>me then raise exception 'Предложение можно создать только от своего имени.'; end if;
    if exists(select 1 from public.profiles where id=me and is_banned) then raise exception 'Ваш аккаунт заблокирован. Вы не можете отправлять предложения.'; end if;
    return new;
  end if;
  select role into old_author_role from public.profiles where id=old.author_id;
  if me_role='owner' then if tg_op='DELETE' then return old; else return new; end if; end if;
  if me_role='admin' and old_author_role='reader' then
    if tg_op<>'DELETE' and new.author_id is distinct from old.author_id then raise exception 'Администратор не может менять автора предложения.'; end if;
    if tg_op='DELETE' then return old; else return new; end if;
  end if;
  if old.author_id=me and old.status in('pending','rejected','approved','pending_update') then
    if tg_op<>'DELETE' and new.author_id is distinct from old.author_id then raise exception 'Нельзя менять автора собственного предложения.'; end if;
    if tg_op='DELETE' then return old; else return new; end if;
  end if;
  raise exception 'Недостаточно прав для этого предложения.';
end $$;
drop trigger if exists community_submission_guard on public.news_submissions;
create trigger community_submission_guard before insert or update or delete on public.news_submissions for each row execute function public.community_submission_guard();

create or replace function public.community_profile_guard()
returns trigger language plpgsql security definer set search_path=''
as $$
declare me uuid:=(select auth.uid()); me_role text;
begin
  if me is null then raise exception 'Требуется авторизация.'; end if;
  select role into me_role from public.profiles where id=me;
  if old.role='owner' and old.id<>me then raise exception 'Профиль владельца защищён.'; end if;
  if new.role<>old.role then raise exception 'Роль изменяется только штатным механизмом владельца.'; end if;
  if (new.is_banned is distinct from old.is_banned or new.ban_reason is distinct from old.ban_reason or new.banned_at is distinct from old.banned_at or new.banned_by is distinct from old.banned_by)
     and not (select public.community_can_manage_user(old.id)) then
    raise exception 'Недостаточно прав для модерации этого пользователя.';
  end if;
  if me<>old.id and (new.nickname is distinct from old.nickname or new.avatar_url is distinct from old.avatar_url or new.bio is distinct from old.bio or new.created_at is distinct from old.created_at) then
    if me_role<>'owner' then raise exception 'Нельзя редактировать чужой профиль.'; end if;
  end if;
  return new;
end $$;
drop trigger if exists community_profile_guard on public.profiles;
create trigger community_profile_guard before update on public.profiles for each row execute function public.community_profile_guard();

create or replace function public.community_delete_comment(p_comment_id bigint)
returns boolean language plpgsql security definer set search_path=''
as $$
declare author_id uuid; me uuid:=(select auth.uid());
begin
  if me is null then raise exception 'Требуется авторизация.'; end if;
  select c.author_id into author_id from public.comments c where c.id=p_comment_id;
  if author_id is null then return false; end if;
  if author_id<>me and not (select public.community_can_manage_user(author_id)) then raise exception 'Недостаточно прав для удаления этого комментария.'; end if;
  delete from public.comments where id=p_comment_id;
  return true;
end $$;
revoke all on function public.community_delete_comment(bigint) from public;
grant execute on function public.community_delete_comment(bigint) to authenticated;

create or replace function public.community_ban_user(p_user_id uuid,p_reason text)
returns boolean language plpgsql security definer set search_path=''
as $$
declare reason text:=trim(coalesce(p_reason,''));
begin
  if (select auth.uid()) is null then raise exception 'Требуется авторизация.'; end if;
  if reason='' then raise exception 'Укажите причину блокировки.'; end if;
  if char_length(reason)>500 then raise exception 'Причина блокировки слишком длинная.'; end if;
  if not (select public.community_can_manage_user(p_user_id)) then raise exception 'Этого пользователя нельзя заблокировать с вашей ролью.'; end if;
  update public.profiles set is_banned=true,ban_reason=reason,banned_at=now(),banned_by=(select auth.uid()) where id=p_user_id;
  return true;
end $$;
revoke all on function public.community_ban_user(uuid,text) from public;
grant execute on function public.community_ban_user(uuid,text) to authenticated;

create or replace function public.community_unban_user(p_user_id uuid)
returns boolean language plpgsql security definer set search_path=''
as $$
begin
  if (select auth.uid()) is null then raise exception 'Требуется авторизация.'; end if;
  if not (select public.community_can_manage_user(p_user_id)) then raise exception 'Этого пользователя нельзя разблокировать с вашей ролью.'; end if;
  update public.profiles set is_banned=false,ban_reason=null,banned_at=null,banned_by=null where id=p_user_id;
  return true;
end $$;
revoke all on function public.community_unban_user(uuid) from public;
grant execute on function public.community_unban_user(uuid) to authenticated;

create or replace function public.community_set_role(p_user_id uuid,p_role text)
returns boolean language plpgsql security definer set search_path=''
as $$
declare old_role text;
begin
  if (select auth.uid()) is null then raise exception 'Требуется авторизация.'; end if;
  if (select public.community_current_role())<>'owner' then raise exception 'Назначать администраторов может только владелец.'; end if;
  if p_role not in('reader','admin') then raise exception 'Можно назначить только reader или admin.'; end if;
  select role into old_role from public.profiles where id=p_user_id;
  if old_role is null then raise exception 'Пользователь не найден.'; end if;
  if old_role='owner' then raise exception 'Роль владельца нельзя изменить.'; end if;
  update public.profiles set role=p_role where id=p_user_id;
  return true;
end $$;
revoke all on function public.community_set_role(uuid,text) from public;
grant execute on function public.community_set_role(uuid,text) to authenticated;

commit;